"""AST Code Sandbox Policy Inspector (OWASP LLM08 - Excessive Agency).

Statically inspects Python code blocks generated by LLMs before passing them to
code interpreter tools or local execution sandboxes.
"""

import ast
from dataclasses import dataclass, field
from typing import List, Optional, Set


@dataclass
class SandboxPolicyResult:
    """Result of static AST code analysis."""
    is_blocked: bool
    violation_code: Optional[str] = None
    violations: List[str] = field(default_factory=list)
    details: str = ""


class CodeSandboxPolicyInspector(ast.NodeVisitor):
    """Static AST analyzer enforcing security sandboxing policies on Python code."""

    DISALLOWED_MODULES: Set[str] = {
        "os", "sys", "subprocess", "socket", "pty", "ctypes", "shutil",
        "importlib", "multiprocessing", "threading", "signal", "tempfile",
        "webbrowser", "winreg", "posix", "pwd", "grp"
    }

    DISALLOWED_BUILTINS: Set[str] = {
        "eval", "exec", "compile", "__import__", "globals", "locals",
        "getattr", "setattr", "delattr", "breakpoint", "memoryview"
    }

    DISALLOWED_ATTRIBUTES: Set[str] = {
        "__builtins__", "__class__", "__base__", "__bases__",
        "__subclasses__", "__mro__", "__globals__", "__code__"
    }

    def __init__(self):
        self._current_violations: List[str] = []

    def inspect(self, code_snippet: str) -> SandboxPolicyResult:
        """Inspect a code snippet for security sandbox violations."""
        if not code_snippet or not code_snippet.strip():
            return SandboxPolicyResult(is_blocked=False)

        try:
            tree = ast.parse(code_snippet)
        except SyntaxError as e:
            # Code cannot be parsed safely
            return SandboxPolicyResult(
                is_blocked=True,
                violation_code="unparseable_malformed_syntax",
                violations=[f"SyntaxError: {str(e)}"],
                details="Generated code failed AST syntactic validation.",
            )

        self._current_violations = []
        self.visit(tree)

        if self._current_violations:
            return SandboxPolicyResult(
                is_blocked=True,
                violation_code="sandbox_policy_violation",
                violations=list(self._current_violations),
                details=f"Code execution policy violation: {self._current_violations[0]}",
            )

        return SandboxPolicyResult(is_blocked=False)

    def visit_Import(self, node: ast.Import):
        for alias in node.names:
            base_mod = alias.name.split(".")[0]
            if base_mod in self.DISALLOWED_MODULES:
                self._current_violations.append(f"disallowed_module_import: {alias.name}")
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom):
        if node.module:
            base_mod = node.module.split(".")[0]
            if base_mod in self.DISALLOWED_MODULES:
                self._current_violations.append(f"disallowed_module_import_from: {node.module}")
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call):
        if isinstance(node.func, ast.Name):
            if node.func.id in self.DISALLOWED_BUILTINS:
                self._current_violations.append(f"disallowed_builtin_call: {node.func.id}")
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute):
        if node.attr in self.DISALLOWED_ATTRIBUTES:
            self._current_violations.append(f"disallowed_dunder_attribute_traversal: {node.attr}")
        self.generic_visit(node)
