"""SQL and NoSQL Injection Guard for Agentic Tools (OWASP LLM02 / LLM08).

Inspects agentic tool call arguments and database queries generated by LLMs to prevent
SQL injection (tautologies, stacked queries, UNION leaks) and NoSQL operator injections.
"""

import re
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class SqlInjectionResult:
    """Result of SQL/NoSQL injection inspection."""
    is_blocked: bool
    violation_code: Optional[str] = None
    threat_category: Optional[str] = None
    detected_patterns: List[str] = field(default_factory=list)
    details: str = ""


class SqlNoSqlInjectionGuard:
    """Inspects SQL/NoSQL strings inside function arguments or prompts."""

    SQL_INJECTION_PATTERNS = [
        # Tautology / Boolean-based bypass
        (r"(?i)\b(?:or|and)\s+['\"]?\d+['\"]?\s*=\s*['\"]?\d+['\"]?", "sql_tautology_bypass"),
        (r"(?i)\b(?:or|and)\s+['\"][a-z0-9]+['\"]\s*=\s*['\"][a-z0-9]+['\"]", "sql_tautology_string"),
        # UNION SELECT data exfiltration
        (r"(?i)\bunion\s+(?:all\s+)?select\b", "sql_union_select_exfiltration"),
        # Stacked / Destructive commands
        (r"(?i);\s*(?:drop\s+table|truncate\s+table|delete\s+from|alter\s+table|grant\s+all)\b", "sql_destructive_stacked_query"),
        # Time-based blind injection / Denial of Service
        (r"(?i)\b(?:waitfor\s+delay|pg_sleep\s*\(|sleep\s*\(|benchmark\s*\()", "sql_time_based_blind_injection"),
        # Information schema probing
        (r"(?i)\bfrom\s+(?:information_schema\.(?:tables|columns)|sqlite_master|sys\.objects)\b", "sql_schema_reconnaissance"),
        # Out-of-band / System interaction
        (r"(?i)\b(?:xp_cmdshell|load_file\s*\(|into\s+(?:outfile|dumpfile))\b", "sql_system_command_execution"),
    ]

    NOSQL_INJECTION_PATTERNS = [
        # MongoDB query selector injection ($where, $regex, $gt)
        (r"['\"]?\$where['\"]?\s*:\s*['\"][^'\"]*['\"]", "nosql_where_clause_injection"),
        (r"['\"]?\$(?:gt|gte|ne|in|nin|regex)['\"]?\s*:\s*['\"]?[^'\"}\]]+['\"]?", "nosql_operator_tampering"),
        # JavaScript evaluation in Mongo
        (r"(?i)\bfunction\s*\(\s*\)\s*\{.*?return\s+true", "nosql_js_function_injection"),
    ]

    def __init__(self):
        self._compiled_sql = [
            (re.compile(pat, re.MULTILINE), code)
            for pat, code in self.SQL_INJECTION_PATTERNS
        ]
        self._compiled_nosql = [
            (re.compile(pat, re.MULTILINE), code)
            for pat, code in self.NOSQL_INJECTION_PATTERNS
        ]

    def inspect(self, query: str) -> SqlInjectionResult:
        """Inspect query string for SQL or NoSQL injection payloads."""
        if not query or not query.strip():
            return SqlInjectionResult(is_blocked=False)

        detected = []

        # Check SQL
        for regex, code in self._compiled_sql:
            if regex.search(query):
                detected.append(code)

        if detected:
            return SqlInjectionResult(
                is_blocked=True,
                violation_code=detected[0],
                threat_category="sql_injection",
                detected_patterns=detected,
                details=f"SQL injection payload detected: {detected[0]}",
            )

        # Check NoSQL
        for regex, code in self._compiled_nosql:
            if regex.search(query):
                detected.append(code)

        if detected:
            return SqlInjectionResult(
                is_blocked=True,
                violation_code=detected[0],
                threat_category="nosql_injection",
                detected_patterns=detected,
                details=f"NoSQL injection payload detected: {detected[0]}",
            )

        return SqlInjectionResult(is_blocked=False)
