"""Agentic Tool Call Argument Validator (OWASP LLM07 - Excessive Agency / Tool Abuse).

Validates agentic function call parameters to prevent Server-Side Request Forgery (SSRF),
directory path traversal, and unauthorized command execution.
"""

import ipaddress
import json
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse


@dataclass
class ToolValidationResult:
    """Result of tool call argument security validation."""
    is_valid: bool
    violation_code: Optional[str] = None
    details: str = ""
    tool_name: Optional[str] = None


class ToolCallValidator:
    """Validates function and tool call parameters generated by or supplied to LLM agents."""

    BLOCKED_HOSTNAMES = {
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
        "::1",
        "metadata.google.internal",
        "instance-data",
    }

    RESTRICTED_SCHEMES = {"file", "gopher", "dict", "ftp", "ldap", "tftp"}

    PATH_TRAVERSAL_REGEX = re.compile(
        r"(?:\.\.[/\\]|\%2e\%2e[/\\]|\.\.;|/(?:etc|proc|sys|root|var/run)/|[a-zA-Z]:[/\\](?:Windows|System32))",
        re.IGNORECASE
    )

    COMMAND_INJECTION_REGEX = re.compile(
        r"(?:[;&|`]\s*(?:rm|curl|wget|cat|sh|bash|powershell|cmd|python)|(?:\$\([^\)]+\)))",
        re.IGNORECASE
    )

    def _is_private_or_loopback_ip(self, host: str) -> bool:
        """Check if an IP address belongs to loopback, private, or cloud metadata ranges."""
        try:
            ip = ipaddress.ip_address(host)
            return (
                ip.is_loopback
                or ip.is_private
                or ip.is_link_local
                or ip.is_reserved
                or str(ip) == "169.254.169.254"
            )
        except ValueError:
            # Host is a domain name, not a raw IP
            return False

    def _validate_url(self, url_str: str) -> Optional[str]:
        """Validate a URL against SSRF vulnerabilities.

        Returns violation message if invalid, None if safe.
        """
        try:
            parsed = urlparse(url_str)
            scheme = (parsed.scheme or "").lower()

            if scheme in self.RESTRICTED_SCHEMES:
                return f"SSRF violation: Dangerous URL scheme '{scheme}' is forbidden."

            hostname = (parsed.hostname or "").lower()
            if not hostname:
                return None

            if hostname in self.BLOCKED_HOSTNAMES or hostname.endswith(".local") or hostname.endswith(".internal"):
                return f"SSRF violation: Access to internal host '{hostname}' is blocked."

            if self._is_private_or_loopback_ip(hostname):
                return f"SSRF violation: Access to private/loopback IP '{hostname}' is blocked."

            return None
        except Exception as err:
            return f"Invalid URL format: {err}"

    def _scan_value(self, val: Any) -> Optional[str]:
        """Recursively scan an argument value for SSRF, path traversal, and command injection."""
        if isinstance(val, str):
            # 1. URL / Protocol Scheme / SSRF check
            if "://" in val or val.startswith(("http://", "https://", "file://", "gopher://", "ftp://")):
                ssrf_err = self._validate_url(val)
                if ssrf_err:
                    return f"ssrf_detected: {ssrf_err}"

            # 2. Path traversal check
            if self.PATH_TRAVERSAL_REGEX.search(val):
                return f"path_traversal_detected: Path parameter contains unauthorized directory traversal sequence '{val}'"

            # 3. Command injection pattern check
            if self.COMMAND_INJECTION_REGEX.search(val):
                return f"command_injection_detected: Argument contains suspicious command chaining syntax '{val}'"

        elif isinstance(val, dict):
            for k, v in val.items():
                err = self._scan_value(v)
                if err:
                    return err

        elif isinstance(val, list):
            for item in val:
                err = self._scan_value(item)
                if err:
                    return err

        return None

    def validate_tool_calls(self, tool_calls: List[Dict[str, Any]]) -> ToolValidationResult:
        """Validate an array of OpenAI tool_calls.

        Args:
            tool_calls: List of tool call objects containing function name and arguments JSON.

        Returns:
            ToolValidationResult indicating allow/block decision.
        """
        if not tool_calls:
            return ToolValidationResult(is_valid=True)

        for call in tool_calls:
            func = call.get("function", {})
            name = func.get("name", "unknown")
            raw_args = func.get("arguments", "{}")

            try:
                args = json.loads(raw_args) if isinstance(raw_args, str) else raw_args
            except Exception:
                # If argument isn't valid JSON, check as raw string
                args = {"raw": raw_args}

            violation = self._scan_value(args)
            if violation:
                code, _, details = violation.partition(": ")
                return ToolValidationResult(
                    is_valid=False,
                    violation_code=code.strip(),
                    details=details.strip() or code.strip(),
                    tool_name=name
                )

        return ToolValidationResult(is_valid=True)
